name: Deploy Vite para GitHub Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  VITE_BASE_URL: ${{ github.event.repository.name }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup do Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Instalar dependências
        run: npm ci

      - name: Build do projeto com Vite
        run: npm run build
        env:
          VITE_BASE_URL: ${{ github.event.repository.name }}

      - name: Upload dos arquivos para deploy
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup nodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Instalar dependências
        run: npm ci

      - name: Instalar playwright e dependências
        run: |
          npx playwright install --with-deps
          npx playwright install chromium

      - name: Iniciar servidor de desenvolvimento
        run: |
          npm run dev &
          sleep 5

      - name: Rodar testes
        run: npx playwright test
        env:
          CI: true
          BASE_URL: http://localhost:8080/balance-on-tap/

      - name: Upload relatório de testes
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  deploy:
    needs: [build, test]
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy para GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4